### ISSUE TITLE
Issue with settings UI

### ISSUE THREAD

**Issue by toomanynights** [Haakjvork/musicbee-sync-lastfm-playcount#1]
Hi.
Either it's just me, or something happened with settings UI of the plugin - I can't see most of the checkboxes that I presume should be there.
https://i.imgur.com/gRETNKJ.png

**Comment by Haakjvork** [comment]
I'll look into it in a couple of days. It's probably due to Windows font size or scaling

**Comment by Haakjvork** [comment]
Changed the UI to open settings in a new Window in version 1.0.7
