### ISSUE TITLE
Playcount discrepancies for the same song title on different albums

### ISSUE THREAD

**Issue by hagnestahill** [Haakjvork/musicbee-sync-lastfm-playcount#2]
Hello
The plugin is working fine, but I have a problem with it.
When I have the same song title from one artist on multiple albums, the playcounts in last fm are summed up and assigned a playcount to each song in musicbee.
In other words, when importing playcounts from LAST FM to MUSICBEE, it seems that the imported album name is not taken into account based on the artist and song title, is that correct?
Can this be fixed?

**Comment by hagnestahill** [comment]
my mistake sorry

**Comment by Haakjvork** [comment]
It's intentional that this plugin deliberitely ignores album name. The original MusicBee Tagging Tool doesn't do that, but I wanted to ignore album name. Cheers!
